name: Build SunamoCollectionOnDrive

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoCollectionOnDrive
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoCollectionOnDrive/SunamoCollectionOnDrive.csproj

    - name: Build
      run: dotnet build SunamoCollectionOnDrive/SunamoCollectionOnDrive.csproj --configuration Release --no-restore

  test:
    name: Test SunamoCollectionOnDrive.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoCollectionOnDrive.Tests/SunamoCollectionOnDrive.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoCollectionOnDrive.Tests/SunamoCollectionOnDrive.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoCollectionOnDrive.Tests/SunamoCollectionOnDrive.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
